# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-02-27 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons_weko', '0006_registrationmetadatamapping_packaging'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationmetadatamapping',
            old_name='packaging',
            new_name='packaging_type',
        ),
    ]
