# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-02-03 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_binderhub', '0002_binderhubtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='binderhubtoken',
            name='jupyterhub_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
