# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-10-26 05:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import osf.models.base
import osf.utils.datetime_aware_jsonfield
import osf.utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('_id', models.CharField(db_index=True, default=osf.models.base.generate_object_id, max_length=24, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted', osf.utils.fields.NonNaiveDateTimeField(blank=True, null=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addons_workflow_node_settings', to='osf.AbstractNode')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.CreateModel(
            name='WorkflowActivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('delegation_tokens', osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder)),
                ('is_enabled', models.BooleanField(default=True)),
                ('activated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_activations', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_activations', to='osf.AbstractNode')),
            ],
            options={
                'ordering': ('node', 'template'),
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.CreateModel(
            name='WorkflowDefinitionSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('definition_id', models.CharField(max_length=255)),
                ('definition_key', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField()),
                ('category', models.CharField(blank=True, max_length=255)),
                ('deployment_id', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('form_schema', osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder)),
                ('definition_metadata', osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder)),
            ],
            options={
                'ordering': ('engine__engine_id', 'definition_key', 'version'),
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.CreateModel(
            name='WorkflowEngine',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('engine_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('gateway_base_url', models.URLField()),
                ('signing_kid', models.CharField(max_length=255)),
                ('verify_ssl', models.BooleanField(default=True)),
                ('token_subject', models.CharField(blank=True, default='rdm-workflow-service', max_length=255)),
                ('token_scope', models.CharField(blank=True, default='workflow::delegate', max_length=255)),
                ('token_audience', models.CharField(blank=True, max_length=255, null=True)),
                ('upload_whitelist_node_ids', osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(blank=True, default=list, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder)),
                ('token_issuer', models.CharField(blank=True, max_length=255, null=True)),
                ('engine_claim', models.CharField(blank=True, default='engine_id', max_length=255)),
                ('engine_claim_value', models.CharField(blank=True, max_length=255, null=True)),
                ('token_lifetime_seconds', models.PositiveIntegerField(default=300)),
                ('request_timeout', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('keyset_url', models.URLField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_engines', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_engines', to='osf.Institution')),
            ],
            options={
                'ordering': ('engine_id',),
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.CreateModel(
            name='WorkflowEngineKey',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('engine_id', models.CharField(db_index=True, max_length=255)),
                ('kid', models.CharField(max_length=255)),
                ('algorithm', models.CharField(max_length=32)),
                ('public_key', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('engine_id', 'kid'),
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.CreateModel(
            name='WorkflowExecutorToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('token_id', models.CharField(max_length=255)),
                ('token_value', osf.utils.fields.EncryptedTextField()),
                ('created_at', osf.utils.fields.NonNaiveDateTimeField(default=django.utils.timezone.now)),
                ('activation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executor_tokens', to='addons_workflow.WorkflowActivation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_executor_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('activation', 'user'),
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('label', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('token_settings', osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder)),
                ('delegation_tokens', osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder)),
                ('is_active', models.BooleanField(default=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='addons_workflow.WorkflowDefinitionSnapshot')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_templates', to='osf.AbstractNode')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('node', 'definition__definition_key'),
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.AlterUniqueTogether(
            name='workflowenginekey',
            unique_together=set([('engine_id', 'kid')]),
        ),
        migrations.AddField(
            model_name='workflowdefinitionsnapshot',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='definition_snapshots', to='addons_workflow.WorkflowEngine'),
        ),
        migrations.AddField(
            model_name='workflowactivation',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='addons_workflow.WorkflowTemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowtemplate',
            unique_together=set([('node', 'definition')]),
        ),
        migrations.AlterUniqueTogether(
            name='workflowexecutortoken',
            unique_together=set([('activation', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='workflowdefinitionsnapshot',
            unique_together=set([('engine', 'definition_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='workflowactivation',
            unique_together=set([('node', 'template')]),
        ),
    ]
