# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtemplate',
            name='visibility',
            field=models.CharField(
                choices=[
                    ('project', 'project'),
                    ('institution', 'institution'),
                    ('public', 'public'),
                ],
                default='project',
                max_length=32,
            ),
        ),
    ]
