# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-03-21 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodesettings',
            name='admin_mailaddr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nodesettings',
            name='process_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nodesettings',
            name='process_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nodesettings',
            name='process_project_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nodesettings',
            name='researcher_mailaddr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nodesettings',
            name='workflow_project_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nodesettings',
            name='workflow_userid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nodesettings',
            name='workflow_valid_userid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
