# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-03-21 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_workflow', '0002_auto_20250321_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodesettings',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
