# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-11-21 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_workflow', '0003_workflowtemplate_auto_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowengine',
            name='label',
            field=models.CharField(default='', max_length=255),
        ),
    ]
