# -*- coding: utf-8 -*-
"""Workflow addon routes."""

from framework.routing import Rule, json_renderer
from website.routes import notemplate

from addons.workflow import views

SHORT_NAME = 'workflow'

page_routes = {
    'rules': [
        Rule(
            [
                f'/<pid>/{SHORT_NAME}',
                f'/<pid>/node/<nid>/{SHORT_NAME}',
            ],
            'get',
            views.project_workflow,
            notemplate,
        ),
    ],
}

api_routes = {
    'rules': [
        Rule(
            ['/workflow/keyset/'],
            'get',
            views.gateway_keyset,
            json_renderer,
        ),
        Rule(
            [
                f'/project/<pid>/{SHORT_NAME}/engines/',
                f'/project/<pid>/node/<nid>/{SHORT_NAME}/engines/',
            ],
            'get',
            views.list_engines,
            json_renderer,
        ),
        Rule(
            ['/workflow/engines/'],
            'post',
            views.upsert_engine,
            json_renderer,
        ),
        Rule(
            ['/workflow/engines/<string:engine_id>/'],
            'get',
            views.retrieve_engine,
            json_renderer,
        ),
        Rule(
            ['/workflow/engines/<string:engine_id>/'],
            'delete',
            views.delete_engine,
            json_renderer,
        ),
        Rule(
            ['/workflow/engines/<string:engine_id>/keys/'],
            'get',
            views.list_engine_keys,
            json_renderer,
        ),
        Rule(
            ['/workflow/engines/<string:engine_id>/keys/'],
            'post',
            views.upsert_engine_key,
            json_renderer,
        ),
        Rule(
            ['/workflow/engines/<string:engine_id>/keys/<string:kid>/'],
            'get',
            views.retrieve_engine_key,
            json_renderer,
        ),
        Rule(
            ['/workflow/engines/<string:engine_id>/keys/<string:kid>/'],
            'delete',
            views.deactivate_engine_key,
            json_renderer,
        ),
        Rule(
            [
                f'/project/<pid>/{SHORT_NAME}/engines/<string:engine_id>/definitions/',
                f'/project/<pid>/node/<nid>/{SHORT_NAME}/engines/<string:engine_id>/definitions/',
            ],
            'get',
            views.list_engine_definitions,
            json_renderer,
        ),
        Rule(
            [
                f'/project/<pid>/{SHORT_NAME}/templates/',
                f'/project/<pid>/node/<nid>/{SHORT_NAME}/templates/',
            ],
            'get',
            views.list_templates,
            json_renderer,
        ),
        Rule(
            [
                f'/project/<pid>/{SHORT_NAME}/templates/',
                f'/project/<pid>/node/<nid>/{SHORT_NAME}/templates/',
            ],
            'post',
            views.upsert_template,
            json_renderer,
        ),
        Rule(
            [
                f'/project/<pid>/{SHORT_NAME}/activations/',
                f'/project/<pid>/node/<nid>/{SHORT_NAME}/activations/',
            ],
            'get',
            views.list_activations,
            json_renderer,
        ),
        Rule(
            [
                f'/project/<pid>/{SHORT_NAME}/templates/<string:template_id>/',
                f'/project/<pid>/node/<nid>/{SHORT_NAME}/templates/<string:template_id>/',
            ],
            'patch',
            views.update_template,
            json_renderer,
        ),
        Rule(
            [
                f'/project/<pid>/{SHORT_NAME}/templates/<string:template_id>/',
                f'/project/<pid>/node/<nid>/{SHORT_NAME}/templates/<string:template_id>/',
            ],
            'delete',
            views.delete_template,
            json_renderer,
        ),
        Rule(
            [
                f'/project/<pid>/{SHORT_NAME}/templates/<string:template_id>/activation/',
                f'/project/<pid>/node/<nid>/{SHORT_NAME}/templates/<string:template_id>/activation/',
            ],
            'get',
            views.retrieve_activation,
            json_renderer,
        ),
        Rule(
            [
                f'/project/<pid>/{SHORT_NAME}/templates/<string:template_id>/activation/',
                f'/project/<pid>/node/<nid>/{SHORT_NAME}/templates/<string:template_id>/activation/',
            ],
            'put',
            views.upsert_activation,
            json_renderer,
        ),
        Rule(
            [
                f'/project/<pid>/{SHORT_NAME}/templates/<string:template_id>/activation/',
                f'/project/<pid>/node/<nid>/{SHORT_NAME}/templates/<string:template_id>/activation/',
            ],
            'delete',
            views.delete_activation,
            json_renderer,
        ),
        Rule(
            [
                f'/project/<pid>/{SHORT_NAME}/templates/<string:template_id>/runs/',
                f'/project/<pid>/node/<nid>/{SHORT_NAME}/templates/<string:template_id>/runs/',
            ],
            'post',
            views.start_run,
            json_renderer,
        ),
        Rule(
            [
                f'/project/<pid>/{SHORT_NAME}/runs/',
                f'/project/<pid>/node/<nid>/{SHORT_NAME}/runs/',
            ],
            'get',
            views.list_runs,
            json_renderer,
        ),
        Rule(
            [
                f'/project/<pid>/{SHORT_NAME}/runs/<string:run_id>/',
                f'/project/<pid>/node/<nid>/{SHORT_NAME}/runs/<string:run_id>/',
            ],
            'delete',
            views.cancel_run,
            json_renderer,
        ),
        Rule(
            [
                f'/project/<pid>/{SHORT_NAME}/tasks/',
                f'/project/<pid>/node/<nid>/{SHORT_NAME}/tasks/',
            ],
            'get',
            views.list_tasks,
            json_renderer,
        ),
        Rule(
            [
                f'/project/<pid>/{SHORT_NAME}/engines/<string:engine_id>/tasks/<string:task_id>/',
                f'/project/<pid>/node/<nid>/{SHORT_NAME}/engines/<string:engine_id>/tasks/<string:task_id>/',
            ],
            'get',
            views.retrieve_task,
            json_renderer,
        ),
        Rule(
            [
                f'/project/<pid>/{SHORT_NAME}/engines/<string:engine_id>/tasks/<string:task_id>/actions/',
                f'/project/<pid>/node/<nid>/{SHORT_NAME}/engines/<string:engine_id>/tasks/<string:task_id>/actions/',
            ],
            'post',
            views.submit_task_action,
            json_renderer,
        ),
        Rule(
            [
                f'/project/<pid>/{SHORT_NAME}/engines/<string:engine_id>/runs/<string:process_instance_id>/notifications/',
                f'/project/<pid>/node/<nid>/{SHORT_NAME}/engines/<string:engine_id>/runs/<string:process_instance_id>/notifications/',
            ],
            'post',
            views.workflow_notification,
            json_renderer,
        ),
        Rule(
            [
                f'/project/<pid>/{SHORT_NAME}/jobs/<string:job_id>/',
                f'/project/<pid>/node/<nid>/{SHORT_NAME}/jobs/<string:job_id>/',
            ],
            'get',
            views.get_job_status,
            json_renderer,
        ),
    ],
    'prefix': '/api/v1',
}
