# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-01-29 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_metadata', '0005_add_index_erad_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='eradrecord',
            name='s_kadai_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='eradrecord',
            index=models.Index(fields=['kenkyusha_no', 's_kadai_id', 'nendo'], name='addons_meta_kenkyus_3b9b64_idx'),
        ),
    ]
