# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-03-19 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons_metadata', '0009_importedaddonsettings'),
        ('addons_metadata', '0009_add_unique_file_metadata'),
    ]

    operations = [
    ]
