# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-24 20:20
from __future__ import unicode_literals

import logging

from django.db import migrations, models

from addons.osfstorage.settings import DEFAULT_REGION_ID, DEFAULT_REGION_NAME

logger = logging.getLogger(__name__)

BATCHSIZE = 5000


def add_regions_to_existing_versions(apps, schema_editor):
    Region = apps.get_model('addons_osfstorage', 'Region')
    FileVersion = apps.get_model('osf', 'FileVersion')
    default_region = Region.objects.get(
        _id=DEFAULT_REGION_ID,
        name=DEFAULT_REGION_NAME,
    )
    max_pk = FileVersion.includable_objects.aggregate(models.Max('pk'))['pk__max']
    if max_pk is not None:
        for offset in range(0, max_pk + 1, BATCHSIZE):
            (FileVersion.includable_objects
                .filter(pk__gte=offset)
                .filter(pk__lt=offset + BATCHSIZE)
                .filter(basefilenode__provider='osfstorage')
                .filter(region__isnull=True)
                .update(region=default_region))
            logger.info(
                'Updated osf_fileversions {}-{}/{}'.format(
                    offset,
                    offset + BATCHSIZE,
                    max_pk,
                )
            )

def remove_regions_from_versions(apps, schema_editor):
    # Reverse migration will remove fk field, no need to reset manually
    pass


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('addons_osfstorage', '0005_region_mfr_url'),
        ('osf', '0130_fileversion_region'),
    ]

    operations = [
        migrations.RunPython(add_regions_to_existing_versions, remove_regions_from_versions)
    ]
