# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-12-17 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0215_auto_20211001_0611'),
        ('osf', '0215_ensure_schemas'),
    ]

    operations = [
    ]
