# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-06-19 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0215_auto_20210417_0945'),
        ('osf', '0215_auto_20210324_0126'),
    ]

    operations = [
    ]
