# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-06-18 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0229_ensure_schema_and_reports'),
        ('osf', '0229_merge_20230617_1021'),
    ]

    operations = [
    ]
