# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-07-25 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0231_ensure_schema_and_reports'),
        ('osf', '0231_merge_20230713_1145'),
    ]

    operations = [
    ]
