# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-08-28 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0232_merge_20230725_0705'),
        ('osf', '0232_merge_20230824_1203'),
    ]

    operations = [
    ]
