# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-08-30 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0234_ensure_schema_and_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportdata',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Stopping', 'Stopping'), ('Checking', 'Checking'), ('Stopped', 'Stopped'), ('Completed', 'Completed'), ('Error', 'Error')], max_length=255),
        ),
        migrations.AlterField(
            model_name='exportdatarestore',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Stopping', 'Stopping'), ('Checking', 'Checking'), ('Stopped', 'Stopped'), ('Completed', 'Completed'), ('Error', 'Error')], max_length=255),
        ),
    ]
