# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-01-30 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0227_alter_filelog_path'),
        ('osf', '0235_auto_20230830_0425'),
        ('osf', '0235_merge_and_ensure_schema_and_reports'),
    ]

    operations = [
    ]
