# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-05-31 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0235_merge_and_ensure_schema_and_reports'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osfuser',
            options={'permissions': (('view_osfuser', 'Can view user details'), ('create_node', 'Can create a new project'))},
        ),
    ]
