# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-07-22 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0237_merge_20240319_1500'),
        ('osf', '0235_ensure_schema_and_reports'),
    ]

    operations = [
    ]
