# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-12-04 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0240_ensure_schema_mappings'),
        ('osf', '0239_ensure_schema_mappings'),
    ]

    operations = [
    ]
