# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-01-31 00:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0241_ensure_schema_mappings'),
    ]

    operations = [
        migrations.AddField(
            model_name='basefilenode',
            name='locked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
