# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-02-07 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0241_merge_20241204_0135'),
        ('osf', '0242_remove_cc0pd_from_erad_schema'),
    ]

    operations = [
    ]
