# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-03-28 09:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0243_ensure_schema_mappings'),
    ]

    operations = [
        migrations.AddField(
            model_name='basefilenode',
            name='locked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrationschemablock',
            name='concealment_page_navigator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrationschemablock',
            name='get_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrationschemablock',
            name='get_retrieval_date',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registrationschemablock',
            name='get_retrieval_title',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registrationschemablock',
            name='get_retrieval_version',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registrationschemablock',
            name='multi_language',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrationschemablock',
            name='required_all_check',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registrationschemablock',
            name='row_addition_caption',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registrationschemablock',
            name='sentence',
            field=models.BooleanField(default=False),
        ),
    ]
