# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-04-17 02:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0246_update_schema_for_manuscript'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationschemablock',
            old_name='auto_date',
            new_name='readonly',
        ),
        migrations.RenameField(
            model_name='registrationschemablock',
            old_name='get_retrieval_date',
            new_name='retrieval_date',
        ),
        migrations.RenameField(
            model_name='registrationschemablock',
            old_name='get_retrieval_title',
            new_name='retrieval_title',
        ),
        migrations.RenameField(
            model_name='registrationschemablock',
            old_name='get_retrieval_version',
            new_name='retrieval_version',
        ),
        migrations.RemoveField(
            model_name='registrationschemablock',
            name='auto_title',
        ),
        migrations.RemoveField(
            model_name='registrationschemablock',
            name='auto_value',
        ),
        migrations.RemoveField(
            model_name='registrationschemablock',
            name='get_edit',
        ),
        migrations.RemoveField(
            model_name='registrationschemablock',
            name='hide_projectmetadata',
        ),
    ]
