# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-07-12 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0252_ensure_schema_and_reports'),
        ('osf', '0244_merge_20250430_2231'),
    ]

    operations = [
    ]
