# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-09-27 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0254_reorder_japan_grant_number'),
        ('osf', '0253_merge_20250712_2206'),
    ]

    operations = [
    ]
