# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-10-30 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0254_reorder_japan_grant_number'),
        ('osf', '0256_ensure_schema_mappings'),
    ]

    operations = [
    ]
