# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2026-02-16 04:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0261_ensure_schema_mappings'),
        ('osf', '0263_merge_20260130_1152'),
    ]

    operations = [
    ]
