# Generated by Django 4.2.30 on 2026-07-30 11:37

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import osf.utils.datetime_aware_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('osf', '0271_merge_20260622_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'permissions': (('modify_brand', 'Can modify brands'),)},
        ),
        migrations.AlterModelOptions(
            name='collectionprovider',
            options={'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='conference',
            options={'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'permissions': (('view_institutional_metrics', 'Can access metrics endpoints for their Institution'),)},
        ),
        migrations.AlterModelOptions(
            name='osfuser',
            options={'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='preprint',
            options={'permissions': (('read_preprint', 'Can read the preprint'), ('write_preprint', 'Can write the preprint'), ('admin_preprint', 'Can manage the preprint'))},
        ),
        migrations.AlterModelOptions(
            name='preprintprovider',
            options={'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='providerassetfile',
            options={'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='registrationprovider',
            options={'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='scheduledbanner',
            options={'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'base_manager_name': 'objects', 'permissions': ()},
        ),
        migrations.AlterModelManagers(
            name='fileversion',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='abstractnode',
            name='access_requests_enabled',
            field=models.BooleanField(blank=True, db_index=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractnode',
            name='external_registration',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='abstractnode',
            name='registered_meta',
            field=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='abstractnode',
            name='registration_responses_migrated',
            field=models.BooleanField(blank=True, db_index=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractnode',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='%(class)ss', to='osf.subject'),
        ),
        migrations.AlterField(
            model_name='abstractnode',
            name='tags',
            field=models.ManyToManyField(related_name='%(class)s_tagged', to='osf.tag'),
        ),
        migrations.AlterField(
            model_name='abstractnode',
            name='type',
            field=models.CharField(choices=[('osf.draftnode', 'draft node'), ('osf.node', 'node'), ('osf.quickfilesnode', 'quick files node'), ('osf.registration', 'registration')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractprovider',
            name='additional_providers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='abstractprovider',
            name='in_sloan_study',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractprovider',
            name='preprint_word',
            field=models.CharField(choices=[('preprint', 'Preprint'), ('paper', 'Paper'), ('thesis', 'Thesis'), ('work', 'Work'), ('none', 'None')], default='preprint', max_length=10),
        ),
        migrations.AlterField(
            model_name='abstractprovider',
            name='reviews_comments_anonymous',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractprovider',
            name='reviews_comments_private',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractprovider',
            name='subjects_acceptable',
            field=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(blank=True, default=list, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='abstractprovider',
            name='type',
            field=models.CharField(choices=[('osf.collectionprovider', 'collection provider'), ('osf.preprintprovider', 'preprint provider'), ('osf.registrationprovider', 'registration provider')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='basefilenode',
            name='is_root',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basefilenode',
            name='tags',
            field=models.ManyToManyField(related_name='%(class)s_tagged', to='osf.tag'),
        ),
        migrations.AlterField(
            model_name='basefilenode',
            name='type',
            field=models.CharField(choices=[('osf.azureblobstoragefile', 'azure blob storage file'), ('osf.azureblobstoragefilenode', 'azure blob storage file node'), ('osf.azureblobstoragefolder', 'azure blob storage folder'), ('osf.bitbucketfile', 'bitbucket file'), ('osf.bitbucketfilenode', 'bitbucket file node'), ('osf.bitbucketfolder', 'bitbucket folder'), ('osf.boxfile', 'box file'), ('osf.boxfilenode', 'box file node'), ('osf.boxfolder', 'box folder'), ('osf.dataversefile', 'dataverse file'), ('osf.dataversefilenode', 'dataverse file node'), ('osf.dataversefolder', 'dataverse folder'), ('osf.dropboxbusinessfile', 'dropbox business file'), ('osf.dropboxbusinessfilenode', 'dropbox business file node'), ('osf.dropboxbusinessfolder', 'dropbox business folder'), ('osf.dropboxfile', 'dropbox file'), ('osf.dropboxfilenode', 'dropbox file node'), ('osf.dropboxfolder', 'dropbox folder'), ('osf.figsharefile', 'figshare file'), ('osf.figsharefilenode', 'figshare file node'), ('osf.figsharefolder', 'figshare folder'), ('osf.githubfile', 'github file'), ('osf.githubfilenode', 'github file node'), ('osf.githubfolder', 'github folder'), ('osf.gitlabfile', 'git lab file'), ('osf.gitlabfilenode', 'git lab file node'), ('osf.gitlabfolder', 'git lab folder'), ('osf.googledrivefile', 'google drive file'), ('osf.googledrivefilenode', 'google drive file node'), ('osf.googledrivefolder', 'google drive folder'), ('osf.iqbrimsfile', 'iqbrims file'), ('osf.iqbrimsfilenode', 'iqbrims file node'), ('osf.iqbrimsfolder', 'iqbrims folder'), ('osf.nextcloudfile', 'nextcloud file'), ('osf.nextcloudfilenode', 'nextcloud file node'), ('osf.nextcloudfolder', 'nextcloud folder'), ('osf.nextcloudinstitutionsfile', 'nextcloud institutions file'), ('osf.nextcloudinstitutionsfilenode', 'nextcloud institutions file node'), ('osf.nextcloudinstitutionsfolder', 'nextcloud institutions folder'), ('osf.ociinstitutionsfile', 'oci institutions file'), ('osf.ociinstitutionsfilenode', 'oci institutions file node'), ('osf.ociinstitutionsfolder', 'oci institutions folder'), ('osf.onedrivebusinessfile', 'one drive business file'), ('osf.onedrivebusinessfilenode', 'one drive business file node'), ('osf.onedrivebusinessfolder', 'one drive business folder'), ('osf.onedrivefile', 'one drive file'), ('osf.onedrivefilenode', 'one drive file node'), ('osf.onedrivefolder', 'one drive folder'), ('osf.osfstoragefile', 'osf storage file'), ('osf.osfstoragefilenode', 'osf storage file node'), ('osf.osfstoragefolder', 'osf storage folder'), ('osf.owncloudfile', 'owncloud file'), ('osf.owncloudfilenode', 'owncloud file node'), ('osf.owncloudfolder', 'owncloud folder'), ('osf.s3compatb3file', 's3 compat b3 file'), ('osf.s3compatb3filenode', 's3 compat b3 file node'), ('osf.s3compatb3folder', 's3 compat b3 folder'), ('osf.s3compatfile', 's3 compat file'), ('osf.s3compatfilenode', 's3 compat file node'), ('osf.s3compatfolder', 's3 compat folder'), ('osf.s3compatinstitutionsfile', 's3 compat institutions file'), ('osf.s3compatinstitutionsfilenode', 's3 compat institutions file node'), ('osf.s3compatinstitutionsfolder', 's3 compat institutions folder'), ('osf.s3compatsigv4file', 's3 compat sig v4 file'), ('osf.s3compatsigv4filenode', 's3 compat sig v4 file node'), ('osf.s3compatsigv4folder', 's3 compat sig v4 folder'), ('osf.s3file', 's3 file'), ('osf.s3filenode', 's3 file node'), ('osf.s3folder', 's3 folder'), ('osf.swiftfile', 'swift file'), ('osf.swiftfilenode', 'swift file node'), ('osf.swiftfolder', 'swift folder'), ('osf.trashedfile', 'trashed file'), ('osf.trashedfilenode', 'trashed file node'), ('osf.trashedfolder', 'trashed folder'), ('osf.wekofile', 'weko file'), ('osf.wekofilenode', 'weko file node'), ('osf.wekofolder', 'weko folder')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collected_types',
            field=models.ManyToManyField(limit_choices_to={'model__in': ['abstractnode', 'basefilenode', 'collection', 'preprint']}, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='collectionsubmission',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='%(class)ss', to='osf.subject'),
        ),
        migrations.AlterField(
            model_name='draftregistration',
            name='registration_responses_migrated',
            field=models.BooleanField(blank=True, db_index=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='draftregistration',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='%(class)ss', to='osf.subject'),
        ),
        migrations.AlterField(
            model_name='draftregistration',
            name='tags',
            field=models.ManyToManyField(related_name='%(class)s_tagged', to='osf.tag'),
        ),
        migrations.AlterField(
            model_name='noderequest',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationsubscription',
            name='email_digest',
            field=models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationsubscription',
            name='email_transactional',
            field=models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationsubscription',
            name='none',
            field=models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preprint',
            name='ever_public',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='preprint',
            name='has_coi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preprint',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='%(class)ss', to='osf.subject'),
        ),
        migrations.AlterField(
            model_name='preprint',
            name='tags',
            field=models.ManyToManyField(related_name='%(class)s_tagged', to='osf.tag'),
        ),
        migrations.AlterField(
            model_name='preprintrequest',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
    ]
