# Generated by Django 4.2.30 on 2026-07-30 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0271_merge_20260622_1735'),
        ('addons_wiki', '0014_wikiimporttask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodesettings',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_node_settings', to='osf.abstractnode'),
        ),
        migrations.AlterField(
            model_name='wikiimporttask',
            name='status',
            field=models.CharField(choices=[('Running', 'Running'), ('Completed', 'Completed'), ('Stopped', 'Stopped'), ('Error', 'Error')], default='Running', max_length=255),
        ),
    ]
