import mock

from dataverse import Connection, Dataverse, Dataset, DataverseFile

from tests.factories import ExternalAccountFactory
from website.addons.base.testing import OAuthAddonTestCaseMixin, AddonTestCase
from website.addons.weko.model import DataverseProvider
from website.addons.weko.tests.factories import DataverseAccountFactory


class DataverseAddonTestCase(OAuthAddonTestCaseMixin, AddonTestCase):
    ADDON_SHORT_NAME = 'dataverse'
    ExternalAccountFactory = DataverseAccountFactory
    Provider = DataverseProvider

    def set_node_settings(self, settings):
        super(DataverseAddonTestCase, self).set_node_settings(settings)
        settings.weko_alias = 'ALIAS2'
        settings.dataverse = 'Example 2'
        settings.dataset_doi = 'doi:12.3456/DVN/00001'
        settings._dataset_id = '18'
        settings.dataset = 'Example (DVN/00001)'
        settings.external_account = self.external_account
        settings.save()


def create_external_account(host='foo.bar.baz', token='doremi-abc-123'):
    """Creates external account for Dataverse with fields populated the same
    way as `weko_add_user_account`"""

    return ExternalAccountFactory(
        provider='dataverse',
        provider_name='Dataverse',
        display_name=host,
        oauth_key=host,
        oauth_secret=token,
        # Note: provider_id in the addon is currently the same as oauth_secret,
        # but here we will let it be generated by sequence to avoid
        # running into duplicate modular ODM entries.
    )


def create_mock_connection(token='snowman-frosty'):
    """
    Create a mock dataverse connection.

    Pass any credentials other than the default parameters and the connection
    will return none.
    """
    if not token == 'snowman-frosty':
        return None

    mock_connection = mock.create_autospec(Connection)

    mock_connection.token = token

    mock_connection.get_wekos.return_value = [
        create_mock_weko('Example 1'),
        create_mock_weko('Example 2'),
        create_mock_weko('Example 3'),
    ]

    def _get_weko(alias):
        return next((
            dataverse for dataverse in mock_connection.get_wekos()
            if alias is not None and dataverse.title[-1] == alias[-1]), None
        )

    mock_connection.get_weko = mock.MagicMock(
        side_effect=_get_weko
    )
    mock_connection.get_weko.return_value = create_mock_weko()

    return mock_connection


def create_mock_weko(title='Example Dataverse 0'):

    mock_weko = mock.create_autospec(Dataverse)

    type(mock_weko).title = mock.PropertyMock(return_value=title)
    type(mock_weko).is_published = mock.PropertyMock(return_value=True)
    type(mock_weko).alias = mock.PropertyMock(
        return_value='ALIAS{}'.format(title[-1])
    )

    mock_weko.get_datasets.return_value = [
        create_mock_dataset('DVN/00001'),
        create_mock_dataset('DVN/00002'),
        create_mock_dataset('DVN/00003'),
    ]

    def _get_dataset_by_doi(doi, timeout=None):
        return next((
            dataset for dataset in mock_weko.get_datasets(timeout=timeout)
            if dataset.doi == doi), None
        )

    mock_weko.get_dataset_by_doi = mock.MagicMock(
        side_effect=_get_dataset_by_doi
    )

    return mock_weko


def create_mock_dataset(id='DVN/12345'):
    mock_dataset = mock.create_autospec(Dataset)

    mock_dataset.citation = 'Example Citation for {0}'.format(id)
    mock_dataset.title = 'Example ({0})'.format(id)
    mock_dataset.doi = 'doi:12.3456/{0}'.format(id)
    mock_dataset.id = '18'
    mock_dataset.get_state.return_value = 'DRAFT'

    def _create_file(name, published=False):
        return create_mock_published_file() if published else create_mock_draft_file()

    def _create_files(published=False):
        return [_create_file('name.txt', published)]

    mock_dataset.get_files = mock.MagicMock(side_effect=_create_files)
    mock_dataset.get_file = mock.MagicMock(side_effect=_create_file)
    mock_dataset.get_file_by_id = mock.MagicMock(side_effect=_create_file)

    # Fail if not given a valid ID
    if 'DVN' in id:
        return mock_dataset

def create_mock_draft_file(id='54321'):
    mock_file = mock.create_autospec(DataverseFile)

    mock_file.name = 'file.txt'
    mock_file.id = id
    mock_file.is_published = False

    return mock_file

def create_mock_published_file(id='54321'):
    mock_file = mock.create_autospec(DataverseFile)

    mock_file.name = 'published.txt'
    mock_file.id = id
    mock_file.is_published = True

    return mock_file

mock_responses = {
    'contents': {
        u'kind': u'item',
        u'name': u'file.txt',
        u'ext': u'.txt',
        u'file_id': u'54321',
        u'urls': {u'download': u'/project/xxxxx/weko/file/54321/download/',
                 u'delete': u'/api/v1/project/xxxxx/weko/file/54321/',
                 u'view': u'/project/xxxxx/weko/file/54321/'},
        u'permissions': {u'edit': False, u'view': True},
        u'addon': u'dataverse',
        u'hasPublishedFiles': True,
        u'state': 'published',
    }
}
